CREATE TABLE IF NOT EXISTS users (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          name varchar(255) NOT NULL,
          email varchar(512) NOT NULL,
          CONSTRAINT pk_user PRIMARY KEY (id),
          CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
        );

CREATE TABLE IF NOT EXISTS requests (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          description varchar(1000) NOT NULL,
          user_id BIGINT NOT NULL,
          created TIMESTAMP NOT NULL,
          CONSTRAINT pk_request PRIMARY KEY (id),
          CONSTRAINT FK_REQUESTS_TO_USERS FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
        );

CREATE TABLE IF NOT EXISTS items (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          name VARCHAR(255),
          description VARCHAR(2000),
          available BOOLEAN,
          owner_id BIGINT NOT NULL,
          request_id BIGINT,
          CONSTRAINT pk_item PRIMARY KEY (id),
          CONSTRAINT FK_ITEMS_TO_USERS FOREIGN KEY(owner_id) REFERENCES users(id) ON DELETE CASCADE,
          CONSTRAINT UQ_ITEM_REQUEST_URL UNIQUE (request_id)
        );

CREATE TABLE IF NOT EXISTS bookings (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
          end_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
          name VARCHAR(100),
          item_id BIGINT NOT NULL,
          booker_id BIGINT NOT NULL,
          status VARCHAR(10),
          CONSTRAINT pk_booking PRIMARY KEY (id),
          CONSTRAINT FK_BOOKING_TO_ITEMS FOREIGN KEY(item_id) REFERENCES items(id) ON DELETE CASCADE,
          CONSTRAINT FK_BOOKING_TO_USERS FOREIGN KEY(booker_id) REFERENCES users(id) ON DELETE CASCADE
        );

CREATE TABLE IF NOT EXISTS comments (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          text VARCHAR(1000) NOT NULL,
          item_id BIGINT NOT NULL,
          author_id BIGINT NOT NULL,
          created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
          CONSTRAINT pk_comment PRIMARY KEY (id),
          CONSTRAINT FK_COMMENT_TO_ITEMS FOREIGN KEY(item_id) REFERENCES items(id) ON DELETE CASCADE,
          CONSTRAINT FK_BOOKING_TO_USERS FOREIGN KEY(author_id) REFERENCES users(id) ON DELETE CASCADE
        );